"""create genres

Revision ID: 5abba1cf34cf
Revises: d2aa7d7bde6f
Create Date: 2025-02-18 15:02:56.328142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5abba1cf34cf'
down_revision = 'd2aa7d7bde6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('name', name=op.f('uq_genres_name'))
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('uq_games_title', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_games_title', ['title'])

    op.drop_table('genres')
    # ### end Alembic commands ###
