"""add genre_id to games

Revision ID: 6d651125b350
Revises: 5abba1cf34cf
Create Date: 2025-02-18 15:13:16.129848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d651125b350'
down_revision = '5abba1cf34cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_games_genre_id_genres'), 'genres', ['genre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_games_genre_id_genres'), type_='foreignkey')
        batch_op.drop_column('genre_id')

    # ### end Alembic commands ###
